name: 'Setup Rust for tests'
description: 'Github action to set up Rust environment and running the tests'
inputs:
  context:
    description: 'Directory to set the context to run the tests'
    required: false
    default: '.'
  run-tests:
    description: 'If we should run the tests or not'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.context }}
    - ${{ inputs.run-tests }}
