on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - uses: actions/checkout@v2
      - name: Enter into code directory
        working-directory: ./rust_code
      - uses: ./
        with:
          rust-version: 'latest'
          run-tests: true