on: [push]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - name: Enter into code directory
        run: cd rust_code
      - uses: actions/checkout@v2
      - uses: albertosml/setup-rust@v1
        with:
          rust-version: 'latest'
          run_tests: true